#!/usr/bin/env php
<?php
use Slince\Collector\CommandUI;

foreach ([__DIR__ . '/../../../vendor/autoload.php'
     , __DIR__ . '/../../vendor/autoload.php'
     , __DIR__ . '/vendor/autoload.php'] as $autoloadFile) {
    if (is_file($autoloadFile)) {
        include $autoloadFile;
        break;
    }
}
//Go
CommandUI::main();